version: '3.8'

services:
  jenkins:
    build: ./jenkins
    container_name: jenkins-dind
    ports:
      - "8080:8080"
      - "50000:50000"
    volumes:
      - jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock  # acceso al Docker del host
    restart: unless-stopped

volumes:
  jenkins_home:
